return {
  -- {
  --   'epwalsh/obsidian.nvim',
  --   -- version = '*',
  --   version = '3.14.7',
  --   ft = 'markdown',
  --   ---@module 'obsidian'
  --   ---@type obsidian.config
  --   opts = {
  --     completion = {
  --       blink = true,
  --     },
  --     -- templates = {
  --     --   folder = 'Developer/templates/',
  --     --   date_format = '%Y-%m-%d',
  --     --   time_format = '%H:%M',
  --     -- },
  --     ui = {
  --       enable = true,
  --       -- enable = false,
  --     },
  --     workspaces = {
  --       {
  --         name = 'personal',
  --         -- path = '/home/dgmastertemple/Obsidian/',
  --         path = '~/Dropbox/Apps/remotely-save/MasterTemple/',
  --       },
  --       {
  --         name = 'library',
  --         path = '~/Dropbox/Apps/remotely-save/Dropbox Library/',
  --       },
  --     },
  --     daily_notes = {
  --       -- Optional, if you keep daily notes in a separate directory.
  --       folder = './Life/Daily Journal/',
  --       -- Optional, if you want to change the date format for the ID of daily notes.
  --       date_format = '%Y-%m-%d',
  --       -- Optional, if you want to change the date format of the default alias of daily notes.
  --       alias_format = '%B %-d, %Y',
  --       -- Optional, default tags to add to each new daily note created.
  --       default_tags = { 'daily-notes' },
  --       -- Optional, if you want to automatically insert a template from your template directory like 'daily.md'
  --       template = 'Daily Note.md',
  --     },
  --     checkbox = {
  --       enabled = true,
  --       create_new = true,
  --       order = { ' ', 'x', '>' },
  --     },
  --   },
  -- },
}
